// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// TAppMonetizeAd is the golang structure for table t_app_monetize_ad.
type TAppMonetizeAd struct {
}

// TAppMonetizeConfig is the golang structure for table t_app_monetize_config.
type TAppMonetizeConfig struct {
}

// TAppMonetizeConfigCopy1 is the golang structure for table t_app_monetize_config_copy1.
type TAppMonetizeConfigCopy1 struct {
}

// TAppPkgList is the golang structure for table t_app_pkg_list.
type TAppPkgList struct {
}

// TAppPkgMonetizeAdparams is the golang structure for table t_app_pkg_monetize_adparams.
type TAppPkgMonetizeAdparams struct {
}

// TAppPkgPutAdparams is the golang structure for table t_app_pkg_put_adparams.
type TAppPkgPutAdparams struct {
}

// TAppPkgSdkParams is the golang structure for table t_app_pkg_sdk_params.
type TAppPkgSdkParams struct {
}

// TAppPutConfig is the golang structure for table t_app_put_config.
type TAppPutConfig struct {
}

// TAppPutConfigCopy1 is the golang structure for table t_app_put_config_copy1.
type TAppPutConfigCopy1 struct {
}

// TAppSelectionConfig is the golang structure for table t_app_selection_config.
type TAppSelectionConfig struct {
}

// TApps is the golang structure for table t_apps.
type TApps struct {
}

// TAuthRule is the golang structure for table t_auth_rule.
type TAuthRule struct {
}

// TCashData is the golang structure for table t_cash_data.
type TCashData struct {
}

// TDynamicConfig is the golang structure for table t_dynamic_config.
type TDynamicConfig struct {
}

// TGameConfigLog is the golang structure for table t_game_config_log.
type TGameConfigLog struct {
}

// TGameEvent is the golang structure for table t_game_event.
type TGameEvent struct {
}

// TGameHost is the golang structure for table t_game_host.
type TGameHost struct {
}

// TGameJson is the golang structure for table t_game_json.
type TGameJson struct {
}

// TGameList is the golang structure for table t_game_list.
type TGameList struct {
}

// TGameModule is the golang structure for table t_game_module.
type TGameModule struct {
}

// TGameModuleTree is the golang structure for table t_game_module_tree.
type TGameModuleTree struct {
}

// TGameModuleTreeField is the golang structure for table t_game_module_tree_field.
type TGameModuleTreeField struct {
}

// TGameModuleTreeTable is the golang structure for table t_game_module_tree_table.
type TGameModuleTreeTable struct {
}

// TGameModuleTreeValue is the golang structure for table t_game_module_tree_value.
type TGameModuleTreeValue struct {
}

// TGameOperateConfig is the golang structure for table t_game_operate_config.
type TGameOperateConfig struct {
}

// TGameVersion is the golang structure for table t_game_version.
type TGameVersion struct {
}

// TModule is the golang structure for table t_module.
type TModule struct {
}

// TModuleTree is the golang structure for table t_module_tree.
type TModuleTree struct {
}

// TModuleTreeField is the golang structure for table t_module_tree_field.
type TModuleTreeField struct {
}

// TModuleTreeTable is the golang structure for table t_module_tree_table.
type TModuleTreeTable struct {
}

// TModuleTreeValue is the golang structure for table t_module_tree_value.
type TModuleTreeValue struct {
}

// TOperateData is the golang structure for table t_operate_data.
type TOperateData struct {
}

// TPutAdparames is the golang structure for table t_put_adparames.
type TPutAdparames struct {
}

// TPutConfig is the golang structure for table t_put_config.
type TPutConfig struct {
}

// TPutConfig1 is the golang structure for table t_put_config1.
type TPutConfig1 struct {
}

// TPutConfigCopy1 is the golang structure for table t_put_config_copy1.
type TPutConfigCopy1 struct {
}

// TUserApps is the golang structure for table t_user_apps.
type TUserApps struct {
}

// TUserGameAuth is the golang structure for table t_user_game_auth.
type TUserGameAuth struct {
}

// TUserLog is the golang structure for table t_user_log.
type TUserLog struct {
}

// TUsers is the golang structure for table t_users.
type TUsers struct {
}
