// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tAppPkgListDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppPkgListDao struct {
	*internal.TAppPkgListDao
}

var (
	// TAppPkgList is globally public accessible object for table t_app_pkg_list operations.
	TAppPkgList = tAppPkgListDao{
		internal.NewTAppPkgListDao(),
	}
)

// Fill with you ideas below.
