// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tAppMonetizeConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppMonetizeConfigDao struct {
	*internal.TAppMonetizeConfigDao
}

var (
	// TAppMonetizeConfig is globally public accessible object for table t_app_monetize_config operations.
	TAppMonetizeConfig = tAppMonetizeConfigDao{
		internal.NewTAppMonetizeConfigDao(),
	}
)

// Fill with you ideas below.
