// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tAppSelectionConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppSelectionConfigDao struct {
	*internal.TAppSelectionConfigDao
}

var (
	// TAppSelectionConfig is globally public accessible object for table t_app_selection_config operations.
	TAppSelectionConfig = tAppSelectionConfigDao{
		internal.NewTAppSelectionConfigDao(),
	}
)

// Fill with you ideas below.
