// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tAppPutConfigCopy1Dao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppPutConfigCopy1Dao struct {
	*internal.TAppPutConfigCopy1Dao
}

var (
	// TAppPutConfigCopy1 is globally public accessible object for table t_app_put_config_copy1 operations.
	TAppPutConfigCopy1 = tAppPutConfigCopy1Dao{
		internal.NewTAppPutConfigCopy1Dao(),
	}
)

// Fill with you ideas below.
