// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tAppMonetizeAdDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppMonetizeAdDao struct {
	*internal.TAppMonetizeAdDao
}

var (
	// TAppMonetizeAd is globally public accessible object for table t_app_monetize_ad operations.
	TAppMonetizeAd = tAppMonetizeAdDao{
		internal.NewTAppMonetizeAdDao(),
	}
)

// Fill with you ideas below.
