// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tAppPkgSdkParamsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppPkgSdkParamsDao struct {
	*internal.TAppPkgSdkParamsDao
}

var (
	// TAppPkgSdkParams is globally public accessible object for table t_app_pkg_sdk_params operations.
	TAppPkgSdkParams = tAppPkgSdkParamsDao{
		internal.NewTAppPkgSdkParamsDao(),
	}
)

// Fill with you ideas below.
