// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tAppPutConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppPutConfigDao struct {
	*internal.TAppPutConfigDao
}

var (
	// TAppPutConfig is globally public accessible object for table t_app_put_config operations.
	TAppPutConfig = tAppPutConfigDao{
		internal.NewTAppPutConfigDao(),
	}
)

// Fill with you ideas below.
