// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tAppMonetizeConfigCopy1Dao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppMonetizeConfigCopy1Dao struct {
	*internal.TAppMonetizeConfigCopy1Dao
}

var (
	// TAppMonetizeConfigCopy1 is globally public accessible object for table t_app_monetize_config_copy1 operations.
	TAppMonetizeConfigCopy1 = tAppMonetizeConfigCopy1Dao{
		internal.NewTAppMonetizeConfigCopy1Dao(),
	}
)

// Fill with you ideas below.
