// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tAppPkgMonetizeAdparamsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAppPkgMonetizeAdparamsDao struct {
	*internal.TAppPkgMonetizeAdparamsDao
}

var (
	// TAppPkgMonetizeAdparams is globally public accessible object for table t_app_pkg_monetize_adparams operations.
	TAppPkgMonetizeAdparams = tAppPkgMonetizeAdparamsDao{
		internal.NewTAppPkgMonetizeAdparamsDao(),
	}
)

// Fill with you ideas below.
