// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tAuthRuleDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tAuthRuleDao struct {
	*internal.TAuthRuleDao
}

var (
	// TAuthRule is globally public accessible object for table t_auth_rule operations.
	TAuthRule = tAuthRuleDao{
		internal.NewTAuthRuleDao(),
	}
)

// Fill with you ideas below.
