// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tGameModuleTreeValueDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tGameModuleTreeValueDao struct {
	*internal.TGameModuleTreeValueDao
}

var (
	// TGameModuleTreeValue is globally public accessible object for table t_game_module_tree_value operations.
	TGameModuleTreeValue = tGameModuleTreeValueDao{
		internal.NewTGameModuleTreeValueDao(),
	}
)

// Fill with you ideas below.
