// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tGameModuleTreeFieldDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tGameModuleTreeFieldDao struct {
	*internal.TGameModuleTreeFieldDao
}

var (
	// TGameModuleTreeField is globally public accessible object for table t_game_module_tree_field operations.
	TGameModuleTreeField = tGameModuleTreeFieldDao{
		internal.NewTGameModuleTreeFieldDao(),
	}
)

// Fill with you ideas below.
