// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tGameConfigLogDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tGameConfigLogDao struct {
	*internal.TGameConfigLogDao
}

var (
	// TGameConfigLog is globally public accessible object for table t_game_config_log operations.
	TGameConfigLog = tGameConfigLogDao{
		internal.NewTGameConfigLogDao(),
	}
)

// Fill with you ideas below.
