// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tGameModuleDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tGameModuleDao struct {
	*internal.TGameModuleDao
}

var (
	// TGameModule is globally public accessible object for table t_game_module operations.
	TGameModule = tGameModuleDao{
		internal.NewTGameModuleDao(),
	}
)

// Fill with you ideas below.
