// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tGameVersionDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tGameVersionDao struct {
	*internal.TGameVersionDao
}

var (
	// TGameVersion is globally public accessible object for table t_game_version operations.
	TGameVersion = tGameVersionDao{
		internal.NewTGameVersionDao(),
	}
)

// Fill with you ideas below.
