// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tModuleDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tModuleDao struct {
	*internal.TModuleDao
}

var (
	// TModule is globally public accessible object for table t_module operations.
	TModule = tModuleDao{
		internal.NewTModuleDao(),
	}
)

// Fill with you ideas below.
