// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tModuleTreeDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tModuleTreeDao struct {
	*internal.TModuleTreeDao
}

var (
	// TModuleTree is globally public accessible object for table t_module_tree operations.
	TModuleTree = tModuleTreeDao{
		internal.NewTModuleTreeDao(),
	}
)

// Fill with you ideas below.
