// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tModuleTreeFieldDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tModuleTreeFieldDao struct {
	*internal.TModuleTreeFieldDao
}

var (
	// TModuleTreeField is globally public accessible object for table t_module_tree_field operations.
	TModuleTreeField = tModuleTreeFieldDao{
		internal.NewTModuleTreeFieldDao(),
	}
)

// Fill with you ideas below.
