// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tModuleTreeValueDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tModuleTreeValueDao struct {
	*internal.TModuleTreeValueDao
}

var (
	// TModuleTreeValue is globally public accessible object for table t_module_tree_value operations.
	TModuleTreeValue = tModuleTreeValueDao{
		internal.NewTModuleTreeValueDao(),
	}
)

// Fill with you ideas below.
