// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tOperateDataDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tOperateDataDao struct {
	*internal.TOperateDataDao
}

var (
	// TOperateData is globally public accessible object for table t_operate_data operations.
	TOperateData = tOperateDataDao{
		internal.NewTOperateDataDao(),
	}
)

// Fill with you ideas below.
