// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tPutAdparamesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tPutAdparamesDao struct {
	*internal.TPutAdparamesDao
}

var (
	// TPutAdparames is globally public accessible object for table t_put_adparames operations.
	TPutAdparames = tPutAdparamesDao{
		internal.NewTPutAdparamesDao(),
	}
)

// Fill with you ideas below.
