// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tPutConfigCopy1Dao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tPutConfigCopy1Dao struct {
	*internal.TPutConfigCopy1Dao
}

var (
	// TPutConfigCopy1 is globally public accessible object for table t_put_config_copy1 operations.
	TPutConfigCopy1 = tPutConfigCopy1Dao{
		internal.NewTPutConfigCopy1Dao(),
	}
)

// Fill with you ideas below.
