// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tPutConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tPutConfigDao struct {
	*internal.TPutConfigDao
}

var (
	// TPutConfig is globally public accessible object for table t_put_config operations.
	TPutConfig = tPutConfigDao{
		internal.NewTPutConfigDao(),
	}
)

// Fill with you ideas below.
