// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tPutConfig1Dao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tPutConfig1Dao struct {
	*internal.TPutConfig1Dao
}

var (
	// TPutConfig1 is globally public accessible object for table t_put_config1 operations.
	TPutConfig1 = tPutConfig1Dao{
		internal.NewTPutConfig1Dao(),
	}
)

// Fill with you ideas below.
