// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tUserLogDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tUserLogDao struct {
	*internal.TUserLogDao
}

var (
	// TUserLog is globally public accessible object for table t_user_log operations.
	TUserLog = tUserLogDao{
		internal.NewTUserLogDao(),
	}
)

// Fill with you ideas below.
