// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/aboutmoon/g/app/dao/internal"
)

// tUserAppsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tUserAppsDao struct {
	*internal.TUserAppsDao
}

var (
	// TUserApps is globally public accessible object for table t_user_apps operations.
	TUserApps = tUserAppsDao{
		internal.NewTUserAppsDao(),
	}
)

// Fill with you ideas below.
