// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"g/app/dao/internal"
)

// tUsersDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tUsersDao struct {
	*internal.TUsersDao
}

var (
	// TUsers is globally public accessible object for table t_users operations.
	TUsers = tUsersDao{
		internal.NewTUsersDao(),
	}
)

// Fill with you ideas below.
