// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// ApDyqqCommonconfigDao is the manager for logic model data accessing and custom defined data operations functions management.
type ApDyqqCommonconfigDao struct {
	Table   string                    // Table is the underlying table name of the DAO.
	Group   string                    // Group is the database configuration group name of current DAO.
	Columns ApDyqqCommonconfigColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// ApDyqqCommonconfigColumns defines and stores column names for table ap_dyqq_commonconfig.
type ApDyqqCommonconfigColumns struct {
	Id          string // 主键
	ConfigName  string // 配置中文名称
	ConfigEname string // 配置英文名称
	ConfigValue string // 配置内容
	ConfigType  string // 配置类型：1:复合数据类型；2:字符串
	IsDelete    string // 是否删除；0:未删除；1:删除
	UpdateTime  string // 更新时间
	CreateTime  string // 插入时间
	IsDeleted   string // 是否删除；0:未删除；1:删除
}

//  apDyqqCommonconfigColumns holds the columns for table ap_dyqq_commonconfig.
var apDyqqCommonconfigColumns = ApDyqqCommonconfigColumns{
	Id:          "id",
	ConfigName:  "config_name",
	ConfigEname: "config_ename",
	ConfigValue: "config_value",
	ConfigType:  "config_type",
	IsDelete:    "is_delete",
	UpdateTime:  "update_time",
	CreateTime:  "create_time",
	IsDeleted:   "is_deleted",
}

// NewApDyqqCommonconfigDao creates and returns a new DAO object for table data access.
func NewApDyqqCommonconfigDao() *ApDyqqCommonconfigDao {
	return &ApDyqqCommonconfigDao{
		Group:   "default",
		Table:   "ap_dyqq_commonconfig",
		Columns: apDyqqCommonconfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ApDyqqCommonconfigDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ApDyqqCommonconfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ApDyqqCommonconfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
