// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// ApDyqqConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
type ApDyqqConfigDao struct {
	Table   string              // Table is the underlying table name of the DAO.
	Group   string              // Group is the database configuration group name of current DAO.
	Columns ApDyqqConfigColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// ApDyqqConfigColumns defines and stores column names for table ap_dyqq_config.
type ApDyqqConfigColumns struct {
	Id            string // 主键
	ConfigName    string // 配置中文名称
	ConfigEname   string // 配置英文名称
	ConfigVersion string // 适用的游戏版本
	ConfigValue   string // 配置内容
	ConfigType    string // 配置类型：1:复合数据类型；2:字符串
	IsDefault     string // 是否为默认配置；1:是；0:否
	UpdateTime    string // 更新时间
	CreateTime    string // 插入时间
	Status        string // 启用状态: 1:启用；0:禁用
	IsDeleted     string // 是否删除；0:未删除；1:删除
}

//  apDyqqConfigColumns holds the columns for table ap_dyqq_config.
var apDyqqConfigColumns = ApDyqqConfigColumns{
	Id:            "id",
	ConfigName:    "config_name",
	ConfigEname:   "config_ename",
	ConfigVersion: "config_version",
	ConfigValue:   "config_value",
	ConfigType:    "config_type",
	IsDefault:     "is_default",
	UpdateTime:    "update_time",
	CreateTime:    "create_time",
	Status:        "status",
	IsDeleted:     "is_deleted",
}

// NewApDyqqConfigDao creates and returns a new DAO object for table data access.
func NewApDyqqConfigDao() *ApDyqqConfigDao {
	return &ApDyqqConfigDao{
		Group:   "default",
		Table:   "ap_dyqq_config",
		Columns: apDyqqConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ApDyqqConfigDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ApDyqqConfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ApDyqqConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
