// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// TAppPutConfigCopy1Dao is the manager for logic model data accessing and custom defined data operations functions management.
type TAppPutConfigCopy1Dao struct {
	Table   string                    // Table is the underlying table name of the DAO.
	Group   string                    // Group is the database configuration group name of current DAO.
	Columns TAppPutConfigCopy1Columns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// TAppPutConfigCopy1Columns defines and stores column names for table t_app_put_config_copy1.
type TAppPutConfigCopy1Columns struct {
}

//  tAppPutConfigCopy1Columns holds the columns for table t_app_put_config_copy1.
var tAppPutConfigCopy1Columns = TAppPutConfigCopy1Columns{}

// NewTAppPutConfigCopy1Dao creates and returns a new DAO object for table data access.
func NewTAppPutConfigCopy1Dao() *TAppPutConfigCopy1Dao {
	return &TAppPutConfigCopy1Dao{
		Group:   "default",
		Table:   "t_app_put_config_copy1",
		Columns: tAppPutConfigCopy1Columns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TAppPutConfigCopy1Dao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TAppPutConfigCopy1Dao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TAppPutConfigCopy1Dao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
