// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// TAppMonetizeConfigCopy1Dao is the manager for logic model data accessing and custom defined data operations functions management.
type TAppMonetizeConfigCopy1Dao struct {
	Table   string                         // Table is the underlying table name of the DAO.
	Group   string                         // Group is the database configuration group name of current DAO.
	Columns TAppMonetizeConfigCopy1Columns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// TAppMonetizeConfigCopy1Columns defines and stores column names for table t_app_monetize_config_copy1.
type TAppMonetizeConfigCopy1Columns struct {
}

//  tAppMonetizeConfigCopy1Columns holds the columns for table t_app_monetize_config_copy1.
var tAppMonetizeConfigCopy1Columns = TAppMonetizeConfigCopy1Columns{}

// NewTAppMonetizeConfigCopy1Dao creates and returns a new DAO object for table data access.
func NewTAppMonetizeConfigCopy1Dao() *TAppMonetizeConfigCopy1Dao {
	return &TAppMonetizeConfigCopy1Dao{
		Group:   "default",
		Table:   "t_app_monetize_config_copy1",
		Columns: tAppMonetizeConfigCopy1Columns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TAppMonetizeConfigCopy1Dao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TAppMonetizeConfigCopy1Dao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TAppMonetizeConfigCopy1Dao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
