// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// TGameModuleTreeTableDao is the manager for logic model data accessing and custom defined data operations functions management.
type TGameModuleTreeTableDao struct {
	Table   string                      // Table is the underlying table name of the DAO.
	Group   string                      // Group is the database configuration group name of current DAO.
	Columns TGameModuleTreeTableColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// TGameModuleTreeTableColumns defines and stores column names for table t_game_module_tree_table.
type TGameModuleTreeTableColumns struct {
}

//  tGameModuleTreeTableColumns holds the columns for table t_game_module_tree_table.
var tGameModuleTreeTableColumns = TGameModuleTreeTableColumns{}

// NewTGameModuleTreeTableDao creates and returns a new DAO object for table data access.
func NewTGameModuleTreeTableDao() *TGameModuleTreeTableDao {
	return &TGameModuleTreeTableDao{
		Group:   "default",
		Table:   "t_game_module_tree_table",
		Columns: tGameModuleTreeTableColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TGameModuleTreeTableDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TGameModuleTreeTableDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TGameModuleTreeTableDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
